version: '3.8'
services:
  # 1. Ứng dụng Spring Boot của bạn
  backend:
    build: .                 # Chỉ cho Docker biết Dockerfile nằm ở thư mục hiện tại
    container_name: ecommerce-api
    ports:
      - "8080:8080"          # Mở port cho API ra ngoài
    depends_on:
      - db                   # Đảm bảo DB chạy lên trước khi Backend chạy
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/phung
      - SPRING_DATASOURCE_USERNAME=Phung
      - SPRING_DATASOURCE_PASSWORD=Phung
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
  # 2. Cơ sở dữ liệu PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Phung
      POSTGRES_PASSWORD: Phung
      POSTGRES_DB: phung
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. Redis Cache
  redis:
    image: redis:7.0-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
